apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-schema-podo-generator
  labels:
    app: json-schema-podo-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-schema-podo-generator
  template:
    metadata:
      labels:
        app: json-schema-podo-generator
    spec:
      containers:
        - name: jspg-restapi
          image: spatacean.com/jspg/rest-api:k8s-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        - name: jspg-webapp
          image: spatacean.com/jspg/webapp:k8s-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: json-schema-podo-generator
  labels:
    app: json-schema-podo-generator
spec:
  selector:
    app: json-schema-podo-generator
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
